Features/body classification lightning module + training pipeline
KalbeDigitalLab/AI-Vision-Lightning-Pipeline pull request #17
Opened 2023-10-23 02:53 UTC by jasonadriann

# Description

Adding lightning module for body part classification using ResNet-18 + the training pipeline

Source:
* [Lightning Module](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html)
* [VinDr-BodyPartXR](https://vindr.ai/datasets/bodypartxr) dataset
* [ResNet-18](https://arxiv.org/abs/1512.03385v1) architecture

New Features:

* Adding ResNet-18 architecture using torch module
* Create lightning module for bodypart classification using ResNet-18
* Create Hydra config for datamodule + model
* Create testing functions for training pipeline

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

The pr has been tested using [pytest](https://docs.pytest.org/en/7.4.x/) and dummy dataset that are being built with [tmp_path_factory](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html). Training is done using Hydra and Lightning.

**Test Configuration**:

* Firmware version:
* Hardware: IdeaPad Gaming 3 + RTX3050

# Checklist:

- [x] Did you make sure title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-10-23 14:20 UTC, haritsahm requested changes
Please add necessary docstrings

2023-10-23 14:20 UTC, haritsahm commented on src/models/components/resnet18.py
> +        x = self.conv1(x)
missing docstring

2023-10-23 14:20 UTC, haritsahm commented on tests/conftest.py
> +    with initialize(version_base='1.3', config_path='../configs'):
missing docstring

2023-10-23 14:20 UTC, haritsahm commented on tests/conftest.py
> +def cfg_bodyresnet18(cfg_bodyresnet_global, tmp_path) -> DictConfig:
missing docstring

2023-10-23 14:20 UTC, haritsahm commented on tests/test_resnet18_models.py
> +    model = ResNet18(1, 5)
missing docstring

2023-10-23 14:20 UTC, haritsahm commented on tests/test_train_bodypartxr.py
> +def test_train_bodypartxr_fast_dev_run(cfg_bodyresnet18, bodypartxr_dummy_test_dataset_dir, bodypartxr_dummy_train_dataset_dir, bodypartxr_dummy_val_dataset_dir):
missing docstrings

2023-10-27 13:02 UTC, jasonadriann commented
Adding several necessary docstrings. Please kindly review the changes

2023-11-02 04:25 UTC, haritsahm reviewed
Will add more features for testing

2023-11-07 02:53 UTC, haritsahm approved these changes
LGTM

2023-11-07 02:53 UTC, merged