Features/bc classification module
KalbeDigitalLab/AI-Vision-Lightning-Pipeline pull request #18
Opened 2023-11-01 09:25 UTC by IstiqomahUswatunH

# Description

Make small modifications to the data module, add a lightning module for breast cancer classification using ResNet-18, and training pipeline with a single train, validation, and test step for a fast development run

- New Features:
1. Small modification to the data module
2. Adding ResNet-18 architecture using torch module
3. Create a lightning module for breast cancer classification using ResNet-18
4. Create Hydra config for data module + model
5. Create testing functions for the training pipeline

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Ran tests using `pytest` to ensure the correctness of the changes.
- [ ] Tested with a dummy dataset created using `temp_path_factory`.
- [ ] Tested the modified data module.
- [ ] Tested the training pipeline

**Test Configuration**:

- Firmware version:
- Hardware: Asus ExpertBook Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
- Toolchain: Visual Studio Code (VSCode)
- SDK: Windows 10

# Checklist:

- [ ] Did you make sure title is self-explanatory and the description concisely explains the PR?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-02 04:29 UTC, haritsahm requested changes
Please check and update the docstrings and comments

2023-11-02 04:29 UTC, haritsahm commented on src/data/bcc_datamodule.py
> +        # print("check setup data_train:", self.data_train)
remove unused debugging function

2023-11-02 04:29 UTC, haritsahm commented on src/data/bcc_datamodule.py
> +        # print("check setup data_val:", self.data_val)
remove unused debugging function

2023-11-02 04:29 UTC, haritsahm commented on src/data/bcc_datamodule.py
> +            # print("check setup data_predict:", self.data_predict)
remove unused debugging function

2023-11-02 04:29 UTC, haritsahm commented on src/data/bcc_datamodule.py
> +    print('check train_dataloader :', train_dataloader)
remove unused debugging function

2023-11-02 04:29 UTC, haritsahm commented on tests/conftest.py
> +    Args:
remove the args and returns. The function is quite clear by name and functionality

2023-11-02 04:29 UTC, haritsahm commented on tests/conftest.py
> +    Returns:
remov returns. The function is quite clear by name and functionality

2023-11-02 07:29 UTC, IstiqomahUswatunH commented
kindly review, please

2023-11-10 07:19 UTC, haritsahm approved these changes
LGTM

2023-11-10 07:20 UTC, merged