ham10000 classification  data module
KalbeDigitalLab/AI-Vision-Lightning-Pipeline pull request #19
Opened 2023-11-01 13:30 UTC by HAikalfebrianp96

# Description

di cabang ini saya membuat data module dan parser

2023-11-07 02:55 UTC, haritsahm commented
Please use the following PR [template](https://github.com/KalbeDigitalLab/AI-Vision-Lightning-Pipeline/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

2023-11-07 02:56 UTC, haritsahm requested changes
Please read the contribution guideline

2023-11-07 02:56 UTC, haritsahm commented on src/data/ham1000_datamodule.py
> +    def __init__(
Missing docstring, use the numpy doc style

2023-11-07 02:56 UTC, haritsahm commented on src/data/components/ham1000_parser.py
> +    Parameters:
Incorrect type docstring style, please use the numpy doc style

2023-11-08 11:22 UTC, closed without merging

2023-11-08 11:22 UTC, HAikalfebrianp96 commented
> Please use the following PR [template](https://github.com/KalbeDigitalLab/AI-Vision-Lightning-Pipeline/blob/main/.github/PULL_REQUEST_TEMPLATE.md)